development:
  adapter: postgresql
  database: speed_trap_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: speed_trap_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: speed_trap_prod
  pool: 5
  timeout: 5000
